# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/zhu_j/Desktop/文件夹/python/晴雨表/单位.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Dia(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(305, 268)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(101, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 77, 150))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.RadioButton = RadioButton(self.widget)
        self.RadioButton.setObjectName("RadioButton")
        self.verticalLayout_2.addWidget(self.RadioButton)
        self.RadioButton_2 = RadioButton(self.widget)
        self.RadioButton_2.setChecked(True)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.verticalLayout_2.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(self.widget)
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.verticalLayout_2.addWidget(self.RadioButton_3)
        self.RadioButton_4 = RadioButton(self.widget)
        self.RadioButton_4.setObjectName("RadioButton_4")
        self.verticalLayout_2.addWidget(self.RadioButton_4)
        self.RadioButton_5 = RadioButton(self.widget)
        self.RadioButton_5.setObjectName("RadioButton_5")
        self.verticalLayout_2.addWidget(self.RadioButton_5)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(101, 181))
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 49, 88))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RadioButton_6 = RadioButton(self.widget1)
        self.RadioButton_6.setObjectName("RadioButton_6")
        self.verticalLayout.addWidget(self.RadioButton_6)
        self.RadioButton_7 = RadioButton(self.widget1)
        self.RadioButton_7.setChecked(True)
        self.RadioButton_7.setObjectName("RadioButton_7")
        self.verticalLayout.addWidget(self.RadioButton_7)
        self.RadioButton_8 = RadioButton(self.widget1)
        self.RadioButton_8.setObjectName("RadioButton_8")
        self.verticalLayout.addWidget(self.RadioButton_8)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PrimaryPushButton = qfluentwidgets.PrimaryPushButton(Dialog)
        self.PrimaryPushButton.setMinimumSize(QtCore.QSize(102, 32))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_2.addWidget(self.PrimaryPushButton)
        self.PushButton = qfluentwidgets.PushButton(Dialog)
        self.PushButton.setMinimumSize(QtCore.QSize(102, 32))
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_2.addWidget(self.PushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.label.setText(_translate("Dialog", "设置单位…"))
        self.groupBox_2.setTitle(_translate("Dialog", "压强"))
        self.RadioButton.setText(_translate("Dialog", "Pa"))
        self.RadioButton_2.setText(_translate("Dialog", "hPa"))
        self.RadioButton_3.setText(_translate("Dialog", "mmHg"))
        self.RadioButton_4.setText(_translate("Dialog", "cmHg"))
        self.RadioButton_5.setText(_translate("Dialog", "bar"))
        self.groupBox.setTitle(_translate("Dialog", "温标"))
        self.RadioButton_6.setText(_translate("Dialog", "K"))
        self.RadioButton_7.setText(_translate("Dialog", "℃"))
        self.RadioButton_8.setText(_translate("Dialog", "℉"))
        self.PrimaryPushButton.setText(_translate("Dialog", "确定"))
        self.PushButton.setText(_translate("Dialog", "取消"))
from qfluentwidgets import RadioButton
