# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '关于.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# 【手工改动记录 · v1.3.1】重新生成本文件后必须补回下面三点：
#   1. 表头里 pyuic5 写回的个人绝对路径改成相对文件名
#      （由 tests/test_repo_hygiene.py::test_no_personal_absolute_paths 守着）
#   2. Dialog.resize 由 310x289 放大 —— 参考文献放不下了
#   3. label_4 / label_6 / label_5 三个单行标签换成只读文本框 self.references
#      （QTextBrowser 可滚动，内容再长也不会被裁掉或撑破窗口），
#      并在 retranslateUi 里用 _REFERENCES_HTML 填充；
#      对应的三行 label setText 已随之删除。


from PySide2 import QtCore, QtGui, QtWidgets

import qfluentwidgets

# 参考文献面板的内容。用 HTML 直接写在这里而不是读外部文件，是为了保证
# 打包成 exe 后它一定在，且"关于框里写的是什么"与源码一起进版本控制。
# 完整清单、每条公式的实测偏差与存疑说明见 docs/精度与参考文献.md。
_REFERENCES_HTML = """
<style>
  body { font-size: 9pt; }
  h4 { margin: 8px 0 2px 0; }
  ul { margin: 0 0 0 16px; padding: 0; }
  li { margin-bottom: 3px; }
</style>

<h4>用来判断"算得准不准"的外部参照</h4>
<ul>
  <li>WMO / Smithsonian 气象表 —— 水面与冰面饱和水汽压参照值
      （WMO 1966 <i>International Meteorological Tables</i>, WMO-No. 188, 1973 修订）</li>
  <li>Murphy, D. M., &amp; Koop, T. (2005). <i>Review of the vapour pressures of ice and
      supercooled water for atmospheric applications.</i> Q. J. R. Meteorol. Soc.,
      <b>131</b>(608), 1539–1565.</li>
  <li>ASHRAE Handbook—Fundamentals, <i>Chapter 1: Psychrometrics</i> ——
      热力学（绝热饱和）湿球温度定义式</li>
  <li>Stull, R. (2011). <i>Wet-Bulb Temperature from Relative Humidity and Air
      Temperature.</i> J. Appl. Meteor. Climatol., <b>50</b>(11), 2267–2269.</li>
</ul>

<h4>14 条饱和水汽压公式的主要出处</h4>
<ul>
  <li><b>WMO-No. 8 (2018), Annex 4.B, 式 (4.B.1) / (4.B.3)</b> ——
      水面 <i>e</i>=6.112·exp(17.62t/(243.12+t))、冰面 <i>e</i>=6.112·exp(22.46t/(272.62+t))，
      与本站 Magnus 水面 / 冰面逐字一致</li>
  <li>Goff, J. A., &amp; Gratch, S. (1946). <i>Low-pressure properties of water from
      −160 to 212 °F.</i> Trans. ASHVE, <b>52</b>, 95–122.　（Goff-Gratch 水面 / 冰面）</li>
  <li>Goff, J. A. (1957). <i>Saturation pressure of water on the new Kelvin temperature
      scale.</i> Trans. ASHVE, <b>63</b>, 347–354.　（Goff 水面）
      注意年份是 <b>1957</b>，不是常被误写的 1965</li>
  <li>Hyland, R. W., &amp; Wexler, A. (1983). <i>Formulations for the thermodynamic
      properties of the saturated phases of H₂O from 173.15 K to 473.15 K.</i>
      ASHRAE Trans., <b>89</b>(2A), 500–519.　（Wexler 水面 / 冰面）
      —— <b>本站两组 Wexler 系数逐项等于本文</b>，不是 Wexler (1976)</li>
  <li>Buck, A. L. (1981). <i>New equations for computing vapor pressure and enhancement
      factor.</i> J. Appl. Meteor., <b>20</b>(12), 1527–1532.　（Buck 水面 / 冰面）</li>
  <li>Buck, A. L. (1996). <i>Buck Research CR-1A User's Manual</i>, Appendix 1 ——
      三参数水面式 <i>e</i>=6.1121·exp[(18.678 − t/234.5)·t/(257.14+t)]，
      本站 <b>Arden-水面</b> 用的是它（v1.3.2 起按原式实现）</li>
  <li>Marti, J., &amp; Mauersberger, K. (1993). <i>A survey and new measurements of ice
      vapor pressure at temperatures between 170 and 250 K.</i> Geophys. Res. Lett.,
      <b>20</b>(5), 363–366.　（Marti 冰面）</li>
  <li>Alduchov, O. A., &amp; Eskridge, R. E. (1996). <i>Improved Magnus form approximation
      of saturation vapor pressure.</i> J. Appl. Meteor., <b>35</b>(4), 601–609.
      　（Magnus / August 系的现代系数；系数归属尚存疑）</li>
  <li>Tetens, O. (1930). <i>Über einige meteorologische Begriffe.</i>
      Z. Geophys., <b>6</b>, 297–309.</li>
  <li>Bolton, D. (1980). <i>The computation of equivalent potential temperature.</i>
      Mon. Wea. Rev., <b>108</b>, 1046–1053.　（抬升凝结高度 LCL）</li>
  <li>周西华, 梁茵 等 (2007). 饱和水蒸气分压力经验公式的比较. <b>26</b>(3), 331–333.</li>
</ul>

<h4>湿球方程的两个系数</h4>
<p>本站解 <i>e</i> = <i>e<sub>w</sub></i> − A·p·(t − t<sub>w</sub>)
（方程本身见 WMO-No. 8, 4.3.1.1 式 (4.1)），A 取
<b>0.000660(1+0.00115·t<sub>w</sub>)</b>（水面）与
<b>0.000582(1+0.00115·t<sub>f</sub>)</b>（冰面/霜球），逐字取自
<b>FAO《Frost Protection》附录 3 式 (A3.15) / (A3.16)</b>
（转引 Fritschen &amp; Gay, 1979），<b>不是 WMO-No. 8 的系数</b>。
WMO 给的是 Assmann 式 A = 6.53×10⁻⁴(1+0.000944·t<sub>w</sub>)（水面，Annex 4.B.8）
与 5.75×10⁻⁴（冰面，4.B.9）。理论值 A ≈ c<sub>p</sub>/(εL) ≈ 6.46×10⁻⁴
（Simões-Moreira, 1999, Meas. Sci. Technol. 10(4)）。
v1.3.2 以前水面用的是 <b>0.000667</b>——那是历史上的笔误（见 Bug 档案 B-02），
改回 FAO 原文的 0.000660 后与 ASHRAE 绝热饱和定义式的最大偏差由 0.452 K 降到 0.424 K，
常温段（0~30 ℃）由 0.29 K 降到 0.25 K。</p>

<h4>v1.3.2 修正的公式问题</h4>
<ul>
  <li><b>Gili-水面</b>：删掉指数里查不到出处的 <b>+0.00141966</b>。它在式子的参考点
      373.15 K 上给出 1016.57 hPa 而不是按定义应有的 1013.25 hPa，自相矛盾；
      legacy 里的 980.66 配的常数应是 lg(1013.25/980.665) = 0.0141966，
      0.00141966 正是它的 1/10。</li>
  <li><b>Arden-水面</b>：系数是 Buck (1996) 的<b>三参数</b>式，此前被塞进两参数族、
      丢掉 −T/234.5 修正项，100 ℃ 处偏 +12.56%。已新增 buck96 三参数族按原式实现，
      1~50 ℃ 内偏差 ≤0.05%。</li>
  <li><b>注册适用域</b>：Buck-水面 80→50 ℃、Arden-水面 100→50 ℃、
      Wexler-冰面 −150→−100 ℃、Marti-冰面 −150→−103 ℃、
      Goff-冰面/Wexler-冰面 上界 +10→0 ℃（0 ℃ 以上不存在冰面）。</li>
  <li><b>焓值</b>：潜热项要用<b>液态水</b>比热 4.186 kJ/(kg·K)，此前误用水汽比热 1.864。</li>
  <li><b>抬升凝结高度</b>：改回 Bolton (1980) 原式（T、T_d 用开尔文），
      25 ℃/Td 15 ℃ 时 13.66 ℃ → 12.72 ℃，与 125(T−T_d) 米经验规则一致。</li>
</ul>

<h4>未能核实到原文的</h4>
<p><b>Gili-水面</b>：气象学文献中查无"吉利公式"这一名称。目前只在中文暖通/冷却塔工程文献里
找到同族公式，其形式为 lg <i>P</i> = 2.0057173 − 3.142305(10³/T − 10³/373.15) +
8.2·lg(373.15/T) − 0.0024804(100 − t)，<b>P 单位 kPa</b>；而
2.0057173 = lg 101.325，即参考值 101.325 kPa = <b>1013.25 hPa</b>，<b>指数里没有常数项</b>。
v1.3.2 已按这个形式实现（前因子 1013.25 + 参考温度 373.15 K + 无常数项）。</p>
<p>另有若干条目只找到汇编转引、未取得原文（Hyland &amp; Wexler 的页码、Buck 1996 手册、
Tetens 1930、Smithsonian 表页），逐条列在
<a href="https://github.com/x1shang/Wetbulb-Calculator/tree/master/docs">docs/</a>
下的《精度与参考文献.md》。</p>

<h4>完整清单</h4>
<p>每条公式的实测偏差、容差怎么定的、以及所有存疑说明，见仓库
<a href="https://github.com/x1shang/Wetbulb-Calculator/tree/master/docs">docs/</a>
目录下的《精度与参考文献.md》。</p>
"""


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # v1.3.1：由 310x289 放大，好放参考文献面板
        Dialog.resize(470, 660)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(201, 16))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(221, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        # 【手工改动 · v1.3.1】原来是 label_4 / label_6 / label_5 三个单行标签，
        # 只够放一条文献（换行还会被裁掉）。换成只读文本框：内容再长也能滚动查看。
        self.references = QtWidgets.QTextBrowser(Dialog)
        self.references.setObjectName("references")
        self.references.setOpenExternalLinks(True)
        self.references.setMinimumSize(QtCore.QSize(0, 320))
        self.verticalLayout.addWidget(self.references)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.ToolButton = qfluentwidgets.ToolButton(Dialog)
        self.ToolButton.setObjectName("ToolButton")
        self.ToolButton.setIcon(qfluentwidgets.FluentIcon.GITHUB)
        self.horizontalLayout.addWidget(self.ToolButton)
        self.PushButton = qfluentwidgets.PushButton(Dialog)
        self.PushButton.setMinimumSize(QtCore.QSize(102, 32))
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于软件"))
        # self.label.setText(_translate("Dialog", "湿球计算器（version1.2.0)"))  # v1.2.2 旧版本号注释保留
        # self.label.setText(_translate("Dialog", "湿球计算器（version1.2.2)"))  # v1.3.0 旧版本号注释保留
        # self.label.setText(_translate("Dialog", "湿球计算器（version1.3.0)"))  # v1.3.1 旧版本号注释保留
        # self.label.setText(_translate("Dialog", "湿球计算器（version1.3.1)"))  # v1.3.2 旧版本号注释保留
        self.label.setText(_translate("Dialog", "湿球计算器（version1.3.2)"))
        self.label_2.setText(_translate("Dialog", "RDFZ降水相态研究性学习小组"))
        self.label_9.setText(_translate("Dialog", "朱嘉赫 王一博 刘思毅 制作"))
        self.label_3.setText(_translate("Dialog", "参考文献（依据值出处）："))
        self.references.setHtml(_REFERENCES_HTML)
        self.label_7.setText(_translate("Dialog", "联系我们！"))
        self.label_8.setText(_translate("Dialog", "Github@x1shang"))
        self.label_10.setText(_translate("Dialog", "给Star →"))
        self.PushButton.setText(_translate("Dialog", "关闭"))
